mocks/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("<str:host_id>/<str:op_code>/", views.MocksViewset.as_view(), name="mocks"),
]

panel/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.labs, name="labs"),
    path('500', views.error500, name="500"),
    path('login', views.login, name="login"),
    path('logout', views.logout, name="logout"),
    path('list', views.order_list, name="order_list"),
    path('qr-code', views.scan_qr, name="scan_qr"),
    path('detail/<int:id>', views.order_detail, name="order_detail"),
    path('order-edit/<int:id>', views.order_edit, name="order_edit"),
    path('transaction', views.exchange_transaction, name="exchange_transaction"),
    path('search', views.order_search, name="order_search"),
    path('update', views.payment_update, name="payment_update"),
]

vaccine/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.utils.translation import ugettext_lazy as _


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("api/v1/mocks/", include("mocks.urls")),
    path('api/v1/sentry-debug/', trigger_error),
    path("admin/vaccine/60cf32c2-6fe4-4970-b0af-2709fb8c3c82/", admin.site.urls),
    path("o/", include("oauth2_provider.urls", namespace="oauth2_provider")),
    path("api/v1/auth/", include("authentication.urls")),
    path("api/v1/order/", include("order.urls")),
    path("api/v1/pay/", include("payment.urls")),
    path("panel/", include(("panel.urls", "panel"), namespace="panel")),
    path("api/v1/exchange/", include(("exchange.urls", "exchange"), namespace="exchange")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
              static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Text to put at the end of each page's <title>.
admin.site.site_title = _("Admin")

# Text to put in each page's <h1> (and above login form).
admin.site.site_header = _("Vaccine | Vaccine Admin Panel")

# Text to put at the top of the admin index page.
admin.site.index_title = _("Vaccine")

panel/models.py
from django.db import models

# Create your models here.

panel/views.py
import logging
from django.contrib.auth import authenticate, login as django_login, logout as django_logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.conf import settings
from utils.functions import use_permission, get_formatted_log

from order.models import DONE, WAITING_FOR_RECEIVING_SECOND_DOSE
from .forms import FilterForm, TransForm, SearchForm
import requests
import json
import datetime
from rest_framework import status

token_key = "987de982kjhssss98733"

users = [
    {
        "username": "test",
        "password": "test"
    }
]

order_status = [
    {
        "OPEN": "open",
        "WAITING_FOR_PAY": "Waiting for Payment",
        "WAITING_FOR_RECEIVING_FIRST_DOSE": "Waiting for check in",
        "DONE": "Completed"
        # "WAITING_FOR_DATA_SUBMISSION": "Waiting For Data Submission",
        # "FULL_PAID": "Full Paid",
        # "WAITING_FOR_PAY": "Waiting for pay",
        # "PAID_20_PERCENT": "Paid 20 Percent",
        # "WAITING_FOR_SETTING_FIRST_DOSE": "Dose 1 not set",
        # "WAITING_FOR_RECEIVING_FIRST_DOSE": "Dose 1 not received",
        # "WAITING_FOR_SETTING_SECOND_DOSE": "Dose 2 not set",
        # "WAITING_FOR_RECEIVING_SECOND_DOSE": "Dose 2 not received",
        # "DONE": "Order Completed"
    }
]

payment_status = [
    {
        "": "Not Paid",
        "FULL": "Paid Online",
        "EXCHANGE": "Paid by Exchange",
        "USDT": "Paid by USDT"
    }
]

NURSE = "NURSE"
SHROFF = "SHROFF"

debug_logger = logging.getLogger("debug_logger")
error_logger = logging.getLogger("info_logger")


# Create your views here.
def error500(request):
    return render(request, "panel/500.html")


def login(request):
    if request.method == "POST":
        response_code = 0
        message = {"message": "", "token": {}}
        username = request.POST['username']
        password = request.POST["password"]

        user = authenticate(username=username, password=password)

        if user is not None and \
                (len(user.groups.filter(name=NURSE)) != 0 or len(user.groups.filter(name=SHROFF)) != 0):
            django_login(request, user)
            message["message"] = "welcome!"
            return HttpResponse(json.dumps(message), status=200, content_type="application/json")

        message["message"] = "authentication error"

        if response_code == 401:
            message["message"] = "your username or password is incorrect"

        debug_logger.debug(get_formatted_log(
            request.path,
            status.HTTP_400_BAD_REQUEST,
            message["message"],
            request.user
        ))

        return HttpResponse(json.dumps(message), status=400, content_type="application/json")

    return render(request, "user/login.html")


@use_permission(["SHROFF"])
def labs(request):
    return redirect("panel:order_list")


def logout(request):
    django_logout(request)
    return redirect("panel:login")


@login_required
def order_list(request):
    # Request String
    requests_string = settings.PANEL_SERVICE_URL + '/api/v1/order/portal/list/'

    # Filtering
    try:
        filter_form = FilterForm(request.GET)
    except Exception as e:
        return redirect("panel:500")

    # Request Json
    request_json = {}

    request_json["API-KEY"] = settings.PORTAL_API_KEY
    if request.GET.get("order_id", None):
        request_json["order_id"] = request.GET.get("order_id")

    if request.GET.get("user_email", None):
        request_json["user_email"] = request.GET.get("user_email")

    if request.GET.get("mobile", None):
        request_json["mobile"] = request.GET.get("mobile")

    if request.GET.get("vaccine_center", None):
        request_json["vaccine_center"] = request.GET.get("vaccine_center")

    if request.GET.get("vaccine_type", None):
        request_json["vaccine_type"] = request.GET.get("vaccine_type")

    if request.GET.get("hotel_name", None):
        request_json["hotel_name"] = request.GET.get("hotel_name")

    if request.GET.get("duration", None):
        request_json["duration"] = request.GET.get("duration")

    # if request.GET.get("from_date", None) and request.GET.get('to_date', None):
    if (request.GET.get("from_date") is not None and "/" in request.GET.get("from_date")) or (
            request.GET.get("to_date") is not None and "/" in request.GET.get("to_date")):
        if request.GET.get('from_date'):
            request_json['from_date'] = str(datetime.datetime.strptime(request.GET.get('from_date'), "%d/%m/%Y").date())
        else:
            request_json['from_date'] = str(datetime.datetime.now().date() - datetime.timedelta(days=1))

        if request.GET.get('to_date'):
            request_json['to_date'] = str(datetime.datetime.strptime(request.GET.get('to_date'), "%d/%m/%Y").date())
        else:
            request_json['to_date'] = str(datetime.datetime.now().date() + datetime.timedelta(days=1))

    if request.GET.get("status", None):
        request_json["status"] = request.GET.get("status")

    if request.GET.get("payment_type", None):
        request_json["payment_type"] = request.GET.get("payment_type")

    is_invalid_response = False

    # Get Response
    try:
        response = requests.post(requests_string, json=request_json,
                                 headers={'API-KEY': settings.PORTAL_API_KEY})
    except Exception as e:
        debug_logger.debug(get_formatted_log(
            request.path,
            status.HTTP_500_INTERNAL_SERVER_ERROR,
            str(e),
            request.user
        ))
        return redirect("panel:500")

    if response.status_code == 400:
        is_invalid_response = True

    parsed_response = json.loads(response.content)

    if len(parsed_response['content']) >= 1:
        for order in parsed_response['content']:
            order['status_val'] = order_status[0][order['status']]
            if order['payment_type'] is not None:
                order['payment_type_val'] = payment_status[0][order['payment_type']]
                order['payment_type_class'] = "apSuccess"
            else:
                order['payment_type_val'] = "Unpaid"
                order['payment_type_class'] = "apFailed"
            if order['is_used_coupon']:
                order['discount'] = float(order['hotel_package']['price']) - float(order['paid_amount'])
            else:
                order['discount'] = "-"

    return render(request, "panel/list.html",
                  {'transactions': parsed_response, 'filter_form': filter_form,
                   'is_invalid_response': is_invalid_response})


@login_required
def order_detail(request, id):
    # Request String
    requests_string = settings.PANEL_SERVICE_URL + '/api/v1/order/portal/detail/'
    vaccine_centers_resource = settings.PANEL_SERVICE_URL + "/api/v1/order/vaccine-center/"
    vaccine_types_resource = settings.PANEL_SERVICE_URL + "/api/v1/order/vaccine-type/"

    # Request Json
    request_json = {}

    request_json["order_id"] = id

    # Get Response
    try:
        response = requests.post(requests_string, json=request_json,
                                 headers={'API-KEY': settings.PORTAL_API_KEY})
    except Exception as e:
        debug_logger.debug(get_formatted_log(
            request.path,
            status.HTTP_500_INTERNAL_SERVER_ERROR,
            str(e),
            request.user
        ))
        return redirect("panel:500")

    try:
        vaccine_centers = requests.post(vaccine_centers_resource,
                                        headers={'API-KEY': settings.PORTAL_API_KEY})
    except Exception as e:
        debug_logger.debug(get_formatted_log(
            request.path,
            status.HTTP_500_INTERNAL_SERVER_ERROR,
            str(e),
            request.user
        ))
        return redirect("panel:500")

    parsed_response = json.loads(response.content)
    if len(parsed_response['content']) >= 1:
        parsed_response['content']['status_val'] = order_status[0][parsed_response['content']['status']]
        if parsed_response['content']['payment_type'] is not None:
            parsed_response['content']['payment_type_val'] = payment_status[0][
                parsed_response['content']['payment_type']]
        else:
            parsed_response['content']['payment_type_val'] = "Unpaid"
        parsed_response['content']['person_number'] = len(parsed_response['content']['persons'])
        parsed_response['content']['payment_remaining'] = float(parsed_response['content']['amount']) - float(
            parsed_response['content']['paid_amount'])
        if parsed_response['content']['is_used_coupon']:
            parsed_response['content']['discount'] = float(
                parsed_response['content']['hotel_package']['price']) - float(parsed_response['content']['paid_amount'])
        else:
            parsed_response['content']['discount'] = "-"

    parsed_vaccine_centers = json.loads(vaccine_centers.content)

    next_step = DONE
    if parsed_response["content"]["status"] == WAITING_FOR_RECEIVING_SECOND_DOSE:
        next_step = DONE

    # Get Vaccines
    try:
        vaccine_types_response = requests.post(vaccine_types_resource, json=request_json,
                                               headers={'API-KEY': settings.PORTAL_API_KEY})
    except Exception as e:
        debug_logger.debug(get_formatted_log(
            request.path,
            status.HTTP_500_INTERNAL_SERVER_ERROR,
            str(e),
            request.user
        ))
        return redirect("panel:500")

    parsed_vaccine_types = json.loads(vaccine_types_response.content)

    return render(request, "panel/detail.html",
                  {'id': id, 'info': parsed_response, "vaccine_centers": parsed_vaccine_centers["content"],
                   "next_step": next_step, "vaccine_types": parsed_vaccine_types["content"]})


@login_required
def order_edit(request, id):

panel/templates/panel/dashboard.html
{% extends "layout/layout.html" %}

{% load static %}

{% block pageHead %}
{% endblock pageHead %}

{% block main %}

    <!--##### START CARD BOX SECTION #####-->
    <div class="container cardBox">
        <form>
            <div class="row justify-content-md-center">
                <div class="col">
                    WELLCOME
                </div>
            </div>
        </form>
    </div>
    <!--##### END CARD BOX SECTION #####-->

{% endblock main %}

panel/templates/panel/exchange_transaction.html
{% extends "panel/layout.html" %}

{% load static %}

{% load i18n %}

{% block pageHead %}
    <link rel='stylesheet' type='text/css' href='{% static "panel/list.css" %}'>
    <link rel='stylesheet' type='text/css' href='{% static "panel/detail.css" %}'>
    <link rel='stylesheet' type='text/css' href='{% static "css/vendors/dataTables.bootstrap4.min.css" %}'>
    <link rel='stylesheet' type='text/css' href='{% static "panel/reports.css" %}'>
    <link rel='stylesheet' type='text/css' href='{% static "panel/datatable.css" %}'>
    <link rel='stylesheet' type='text/css' href='{% static "css/vendors/bootstrap-select.min.css" %}'>
    <link rel="stylesheet" type="text/css" href="{% static "css/vendors/bootstrap-datepicker.min.css" %}">

    <script rel="script" type="application/javascript"
            src="{% static "script/vendors/jalali-moment.browser.js" %}"></script>
    <script rel="script" type="application/javascript"
            src="{% static "script/vendors/bootstrap-datepicker.min.js" %}"></script>
    <script src='{% static "script/vendors/jquery.dataTables.min.js" %}'></script>
    <script src='{% static "script/vendors/bootstrap-select.min.js" %}'></script>

{% endblock pageHead %}

{% block main %}

    <!--##### START TAB PANEL HEADER SECTION #####-->
    <div class="container">
        <div class="row justify-content-md-center apTabPanel">
            <div class="col">
                <a href="{% url 'panel:order_search' %}">
                    <div class="apTabTitle">{% trans 'Search Order' %}</div>
                </a>
            </div>
            <div class="col">
                <a href="{% url 'panel:exchange_transaction' %}">
                    <div class="apTabTitle active">{% trans 'Transaction List' %}</div>
                </a>
            </div>
        </div>
    </div>
    <!--##### END TAB PANEL HEADER SECTION #####-->

    <div class="container cardBox">

        <!--##### START RESULT FILTER SECTION #####-->
        <div class="row dataTableSearch">
            <form id="filter_form" action="" method="get" style="width: 100%">
                <div class="form-row">
                    <div class="col-sm-6 col-lg-3 apFilterItem">
                        {{ filter_form.payment_id }}
                    </div>
                    <div class="col-sm-6 col-lg-3 apFilterItem">
                        {{ filter_form.from_date }}
                    </div>
                    <div class="col-sm-6 col-lg-3 apFilterItem">
                        {{ filter_form.to_date }}
                    </div>
                </div>

                <!--##### START ّ Filter RESULT SECTION #####-->
                <div class="row dataTableFilter justify-content-md-end mb-4">
                    <!--
                    <div class="col-sm-6 col-lg-3 apFilterItem">
                        <button id="export_to_xls" class="btn apButton apButton--download">{% trans "export" %}</button>
                    </div>
                    -->
                    <div class="col-sm-6 col-lg-3 apFilterItem">
                        <button class="btn apButton" type="submit">{% trans "filter" %}</button>
                    </div>
                </div>
                <!--##### End Filter RESULT SECTION #####-->
            </form>
        </div>
        <!--##### END RESULT FILTER SECTION #####-->

        <!--##### START RESULT DATA TABLE SECTION #####-->
        <div class="row justify-content-md-center mt-5">

            {% if not is_invalid_response %}
                {% if transactions.content|length != 0 %}
                    <div class="col apPaginateTbl">
                        <div class="table-responsive">
                            <table id="example" class="apTbl">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>{% trans 'Payment Id' %}</th>
                                    <th>{% trans 'Payment Date' %}</th>
                                    <th>{% trans 'Amount' %}</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for data in transactions.content %}
                                    <tr>
                                        <td>{{ 1|add:forloop.counter0 }}</td>
                                        <td>{{ data.order.code }}</td>
                                        <td>{{ data.created_at|slice:"0:10" }}</td>
                                        <td>{{ data.order.amount }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>

                        <!--
                        <div class="row">
                            <div class="col-sm-12 col-md-5">
                                <div class="dataTables_info" role="status" aria-live="polite">
                                    view {{ transactions.pagination.start_index }}
                                    to {{ transactions.pagination.end_index }}
                                    from {{ transactions.pagination.total_index }}
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-7">
                                {% if transactions.pagination.has_other_pages %}
                                    <div class="dataTables_paginate paging_simple_numbers">
                                        {% if transactions.pagination.has_previous %}
                                            <a class="paginate_button page-item previous"
                                               href="{{ request.get_full_path }}&page={{ transactions.pagination.previous_page_number }}"></a>
                                        {% else %}
                                            <a class="paginate_button page-item previous disabled" href="#"></a>
                                        {% endif %}
                                        {% if transactions.pagination.has_next %}
                                            <a class="paginate_button page-item next"
                                               href="{{ request.get_full_path }}&page={{ transactions.pagination.next_page_number }}"></a>
                                        {% else %}
                                            <a class="paginate_button page-item next disabled" href="#"></a>
                                        {% endif %}
                                        <div class="clearfix"></div>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                        -->

                    </div>
                {% else %}
                    <div class="col apPaginateTbl text-center apUnknown">
                        {% trans "No Result" %}
                    </div>
                {% endif %}
            {% endif %}

        </div>
        <!--##### END RESULT DATA TABLE SECTION #####-->

    </div>

    <!-- Modal -->
    <div class="modal fade" id="errorModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body" style="text-align: center;font-weight: bold;padding: 30px 0;">
                    {% trans "لطفا بازه زمانی مورد نظر خود را انتخاب کنید." %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">بستن</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            $('.apTabTitle').on('click', function () {
                $('.apTabTitle').removeClass('active');
                $(this).toggleClass('active');
            });
        });

        $(document).ready(function () {

            $("#from_date").datepicker({
                changeMonth: true,
                changeYear: true,
                yearRange: '2020:2030',
                dateFormat: 'dd/mm/yy'
            });
            $("#to_date").datepicker({
                changeMonth: true,
                changeYear: true,
                yearRange: '2020:2030',
                dateFormat: 'dd/mm/yy'
            });

        });
    </script>

{% endblock main %}

panel/templates/panel/order_search.html
{% extends "panel/layout.html" %}

{% load static %}

{% load i18n %}

{% block pageHead %}
    <link rel='stylesheet' type='text/css' href='{% static "panel/list.css" %}'>
    <link rel='stylesheet' type='text/css' href='{% static "panel/detail.css" %}'>
    <link rel='stylesheet' type='text/css' href='{% static "css/vendors/dataTables.bootstrap4.min.css" %}'>
    <link rel='stylesheet' type='text/css' href='{% static "panel/reports.css" %}'>
    <link rel='stylesheet' type='text/css' href='{% static "panel/datatable.css" %}'>
    <link rel='stylesheet' type='text/css' href='{% static "css/vendors/bootstrap-select.min.css" %}'>
    <link rel="stylesheet" type="text/css" href="{% static "css/vendors/bootstrap-datepicker.min.css" %}">

    <script rel="script" type="application/javascript"
            src="{% static "script/vendors/jalali-moment.browser.js" %}"></script>
    <script rel="script" type="application/javascript"
            src="{% static "script/vendors/bootstrap-datepicker.min.js" %}"></script>
    <script rel="script" type="application/javascript"
            src="{% static "script/vendors/bootstrap-datepicker.fa.min.js" %}"></script>
    <script src='{% static "script/vendors/jquery.dataTables.min.js" %}'></script>
    <script src='{% static "script/vendors/bootstrap-select.min.js" %}'></script>

{% endblock pageHead %}

{% block main %}

    <!--##### START TAB PANEL HEADER SECTION #####-->
    <div class="container">
        <div class="row justify-content-md-center apTabPanel">
            <div class="col">
                <a href="{% url 'panel:order_search' %}">
                    <div class="apTabTitle active">{% trans 'Search Order' %}</div>
                </a>
            </div>
            <div class="col">
                <a href="{% url 'panel:exchange_transaction' %}">
                    <div class="apTabTitle">{% trans 'Transaction List' %}</div>
                </a>
            </div>
        </div>
    </div>
    <!--##### END TAB PANEL HEADER SECTION #####-->

    <div class="container cardBox">

        <!--##### START RESULT FILTER SECTION #####-->
        <div class="row dataTableSearch">
            <form id="filter_form" action="" method="get" style="width: 100%">
                <div class="form-row">
                    <div class="col-sm-6 col-lg-9 apFilterItem">
                        {{ filter_form.payment_id }}
                    </div>
                    <div class="col-sm-6 col-lg-3 apFilterItem">
                        <button type="submit" class="btn apButton">Search</button>
                    </div>
                </div>
            </form>
        </div>
        <!--##### END RESULT FILTER SECTION #####-->

        <!--##### START RESULT DATA TABLE SECTION #####-->
        <div class="row justify-content-md-center mt-5">

            {% if not is_invalid_response %}
                {% if result.content|length != 0 %}

                    <div class="col apPaginateTbl">
                    <p class="h4">Payment Info</p>
                    <hr class="my-12"/>
                    <form id="confirm_form" action="" method="get" style="width: 100%">
                        {% csrf_token %}
                        <div class="row dataTableSearch">
                            <div class="col-sm-6 col-lg-3 apFilterItem">
                                <label for="email">Payment Id</label>
                                <input type="text" name="payment_id" id="payment_id" class="form-control-plaintext"
                                       value="{{ result.content.0.code }}"
                                       readonly>
                            </div>
                            <div class="col-sm-6 col-lg-3 apFilterItem">
                                <label for="email">Order Id</label>
                                <input type="text" name="order_id" id="order_id" class="form-control-plaintext"
                                       value="{{ result.content.0.id }}"
                                       readonly>
                                <input type="hidden" name="exchange_id" id="exchange_id" class="form-control-plaintext"
                                       value="{{ result.content.1.exchange_id }}"
                                       readonly>
                            </div>
                        </div>
                        <div class="row dataTableSearch">
                            <div class="col-sm-6 col-lg-3 apFilterItem">
                                <label for="email">Total Person</label>
                                <input type="text" name="user_name" id="user_name" class="form-control-plaintext"
                                       value="{{ result.content.0.hotel_package.total_person }}"
                                       readonly>
                            </div>
                            <div class="col-sm-6 col-lg-3 apFilterItem">
                                <label for="email">Mobile</label>
                                <input type="text" name="user_mobile" id="user_mobile" class="form-control-plaintext"
                                       value="{{ result.content.0.user.phone }}"
                                       readonly>
                            </div>
                            <div class="col-sm-6 col-lg-3 apFilterItem">
                                <label for="email">Email</label>
                                <input type="text" name="user_email" id="user_email" class="form-control-plaintext"
                                       value="{{ result.content.0.user.email }}"
                                       readonly>
                            </div>
                            <div class="col-sm-6 col-lg-3 apFilterItem">
                                <label for="email">Payable Amount</label>
                                <input type="text" name="pay_amount" id="pay_amount" class="form-control-plaintext"
                                       value="{{ result.content.0.amount }} EUR"
                                       readonly>
                            </div>
                        </div>
                        <div class="row dataTableSearch justify-content-md-end mb-4 mt-5">
                            <div class="col-sm-6 col-lg-3 apFilterItem">
                                <a class="btn apButton" href="#" data-toggle="modal"
                                   data-target="#areYouSure">{% trans "Pay" %}</a>
                            </div>
                        </div>
                    </form>
                {% elif result.content == "" %}
                    <div class="col apPaginateTbl text-center apUnknown">
                    </div>
                {% else %}
                    <div class="col apPaginateTbl text-center apUnknown">
                        {% trans "Invalid Payment ID" %}
                    </div>
                {% endif %}
            {% endif %}
            </div>
            <!--##### END RESULT DATA TABLE SECTION #####-->

        </div>


        <!-- Modal -->
        <div class="modal fade" id="areYouSure" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-body" style="text-align: center;font-weight: bold;padding: 30px 0;">
                        {% trans "Are You Sure?" %}
                    </div>
                    <div id="loading" class="wrap-login__loading-wrapper" style="text-align: center">
                        <div class="wrap-login__loading-wrapper__loading spinner-grow" role="status">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" id="payConfirm" class="btn btn-primary">{% trans "Yes" %}</button>
                        <button type="button" id="payDismiss" class="btn btn-secondary"
                                data-dismiss="modal">{% trans "No" %}</button>
                    </div>
                </div>
            </div>
        </div>


        <script>
            $(document).ready(function () {
                $('.apTabTitle').on('click', function () {
                    $('.apTabTitle').removeClass('active');
                    $(this).toggleClass('active');
                });
            });

            $(document).ready(function () {
                {#$('#example').DataTable();#}

                $("#fromDate").datepicker({
                    changeMonth: true,
                    changeYear: true,
                    yearRange: '1390:1420',
                    dateFormat: 'yy/mm/dd',
                    maxDate: moment(new Date()).format('jYYYY/jMM/jDD')
                });
                $("#toDate").datepicker({
                    changeMonth: true,
                    changeYear: true,
                    yearRange: '1390:1420',
                    dateFormat: 'yy/mm/dd',
                    maxDate: moment(new Date()).format('jYYYY/jMM/jDD')
                });

                $('#areYouSore').on('show.bs.modal', function (event) {
                });

                $("#loading").css("display", "none");


                $('#payConfirm').click(function () {
                    $("#payConfirm").prop("disabled",true);
                    $('#confirm_form').submit();
                });

                $('#confirm_form').on('submit', function (event) {
                    event.preventDefault();
                    $("#loading").css("display", "block");

                    var data = $('#confirm_form').serializeArray();
                    $.post("{% url "panel:payment_update" %}", data, function () {
                        console.log("success");
                        window.location.href = "{% url "panel:exchange_transaction" %}";
                    })
                        .done(function () {
                            console.log("done");
                            $('#payDismiss').click();
                        })
                        .fail(function () {
                            console.log("Incorrect request");
                        });

                });

            });
        </script>

{% endblock main %}