mocks/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("<str:host_id>/<str:op_code>/", views.MocksViewset.as_view(), name="mocks"),
]

panel/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.labs, name="labs"),
    path('500', views.error500, name="500"),
    path('login', views.login, name="login"),
    path('logout', views.logout, name="logout"),
    path('list', views.order_list, name="order_list"),
    path('qr-code', views.scan_qr, name="scan_qr"),
    path('detail/<int:id>', views.order_detail, name="order_detail"),
    path('order-edit/<int:id>', views.order_edit, name="order_edit"),
    path('transaction', views.exchange_transaction, name="exchange_transaction"),
    path('search', views.order_search, name="order_search"),
    path('update', views.payment_update, name="payment_update"),
]

vaccine/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.utils.translation import ugettext_lazy as _


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("api/v1/mocks/", include("mocks.urls")),
    path('api/v1/sentry-debug/', trigger_error),
    path("admin/vaccine/60cf32c2-6fe4-4970-b0af-2709fb8c3c82/", admin.site.urls),
    path("o/", include("oauth2_provider.urls", namespace="oauth2_provider")),
    path("api/v1/auth/", include("authentication.urls")),
    path("api/v1/order/", include("order.urls")),
    path("api/v1/pay/", include("payment.urls")),
    path("panel/", include(("panel.urls", "panel"), namespace="panel")),
    path("api/v1/exchange/", include(("exchange.urls", "exchange"), namespace="exchange")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
              static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Text to put at the end of each page's <title>.
admin.site.site_title = _("Admin")

# Text to put in each page's <h1> (and above login form).
admin.site.site_header = _("Vaccine | Vaccine Admin Panel")

# Text to put at the top of the admin index page.
admin.site.index_title = _("Vaccine")

panel/models.py
from django.db import models

# Create your models here.

panel/views.py
import logging
from django.contrib.auth import authenticate, login as django_login, logout as django_logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.conf import settings
from utils.functions import use_permission, get_formatted_log

from order.models import DONE, WAITING_FOR_RECEIVING_SECOND_DOSE
from .forms import FilterForm, TransForm, SearchForm
import requests
import json
import datetime
from rest_framework import status

token_key = "987de982kjhssss98733"

users = [
    {
        "username": "test",
        "password": "test"
    }
]

order_status = [
    {
        "OPEN": "open",
        "WAITING_FOR_PAY": "Waiting for Payment",
        "WAITING_FOR_RECEIVING_FIRST_DOSE": "Waiting for check in",
        "DONE": "Completed"
        # "WAITING_FOR_DATA_SUBMISSION": "Waiting For Data Submission",
        # "FULL_PAID": "Full Paid",
        # "WAITING_FOR_PAY": "Waiting for pay",
        # "PAID_20_PERCENT": "Paid 20 Percent",
        # "WAITING_FOR_SETTING_FIRST_DOSE": "Dose 1 not set",
        # "WAITING_FOR_RECEIVING_FIRST_DOSE": "Dose 1 not received",
        # "WAITING_FOR_SETTING_SECOND_DOSE": "Dose 2 not set",
        # "WAITING_FOR_RECEIVING_SECOND_DOSE": "Dose 2 not received",
        # "DONE": "Order Completed"
    }
]

payment_status = [
    {
        "": "Not Paid",
        "FULL": "Paid Online",
        "EXCHANGE": "Paid by Exchange",
        "USDT": "Paid by USDT"
    }
]

NURSE = "NURSE"
SHROFF = "SHROFF"

debug_logger = logging.getLogger("debug_logger")
error_logger = logging.getLogger("info_logger")


# Create your views here.
def error500(request):
    return render(request, "panel/500.html")


def login(request):
    if request.method == "POST":
        response_code = 0
        message = {"message": "", "token": {}}
        username = request.POST['username']
        password = request.POST["password"]

        user = authenticate(username=username, password=password)

        if user is not None and \
                (len(user.groups.filter(name=NURSE)) != 0 or len(user.groups.filter(name=SHROFF)) != 0):
            django_login(request, user)
            message["message"] = "welcome!"
            return HttpResponse(json.dumps(message), status=200, content_type="application/json")

        message["message"] = "authentication error"

        if response_code == 401:
            message["message"] = "your username or password is incorrect"

        debug_logger.debug(get_formatted_log(
            request.path,
            status.HTTP_400_BAD_REQUEST,
            message["message"],
            request.user
        ))

        return HttpResponse(json.dumps(message), status=400, content_type="application/json")

    return render(request, "user/login.html")


@use_permission(["SHROFF"])
def labs(request):
    return redirect("panel:order_list")


def logout(request):
    django_logout(request)
    return redirect("panel:login")


@login_required
def order_list(request):
    # Request String
    requests_string = settings.PANEL_SERVICE_URL + '/api/v1/order/portal/list/'

    # Filtering
    try:
        filter_form = FilterForm(request.GET)
    except Exception as e:
        return redirect("panel:500")

    # Request Json
    request_json = {}

    request_json["API-KEY"] = settings.PORTAL_API_KEY
    if request.GET.get("order_id", None):
        request_json["order_id"] = request.GET.get("order_id")

    if request.GET.get("user_email", None):
        request_json["user_email"] = request.GET.get("user_email")

    if request.GET.get("mobile", None):
        request_json["mobile"] = request.GET.get("mobile")

    if request.GET.get("vaccine_center", None):
        request_json["vaccine_center"] = request.GET.get("vaccine_center")

    if request.GET.get("vaccine_type", None):
        request_json["vaccine_type"] = request.GET.get("vaccine_type")

    if request.GET.get("hotel_name", None):
        request_json["hotel_name"] = request.GET.get("hotel_name")

    if request.GET.get("duration", None):
        request_json["duration"] = request.GET.get("duration")

    # if request.GET.get("from_date", None) and request.GET.get('to_date', None):
    if (request.GET.get("from_date") is not None and "/" in request.GET.get("from_date")) or (
            request.GET.get("to_date") is not None and "/" in request.GET.get("to_date")):
        if request.GET.get('from_date'):
            request_json['from_date'] = str(datetime.datetime.strptime(request.GET.get('from_date'), "%d/%m/%Y").date())
        else:
            request_json['from_date'] = str(datetime.datetime.now().date() - datetime.timedelta(days=1))

        if request.GET.get('to_date'):
            request_json['to_date'] = str(datetime.datetime.strptime(request.GET.get('to_date'), "%d/%m/%Y").date())
        else:
            request_json['to_date'] = str(datetime.datetime.now().date() + datetime.timedelta(days=1))

    if request.GET.get("status", None):
        request_json["status"] = request.GET.get("status")

    if request.GET.get("payment_type", None):
        request_json["payment_type"] = request.GET.get("payment_type")

    is_invalid_response = False

    # Get Response
    try:
        response = requests.post(requests_string, json=request_json,
                                 headers={'API-KEY': settings.PORTAL_API_KEY})
    except Exception as e:
        debug_logger.debug(get_formatted_log(
            request.path,
            status.HTTP_500_INTERNAL_SERVER_ERROR,
            str(e),
            request.user
        ))
        return redirect("panel:500")

    if response.status_code == 400:
        is_invalid_response = True

    parsed_response = json.loads(response.content)

    if len(parsed_response['content']) >= 1:
        for order in parsed_response['content']:
            order['status_val'] = order_status[0][order['status']]
            if order['payment_type'] is not None:
                order['payment_type_val'] = payment_status[0][order['payment_type']]
                order['payment_type_class'] = "apSuccess"
            else:
                order['payment_type_val'] = "Unpaid"
                order['payment_type_class'] = "apFailed"
            if order['is_used_coupon']:
                order['discount'] = float(order['hotel_package']['price']) - float(order['paid_amount'])
            else:
                order['discount'] = "-"

    return render(request, "panel/list.html",
                  {'transactions': parsed_response, 'filter_form': filter_form,
                   'is_invalid_response': is_invalid_response})


@login_required
def order_detail(request, id):
    # Request String
    requests_string = settings.PANEL_SERVICE_URL + '/api/v1/order/portal/detail/'
    vaccine_centers_resource = settings.PANEL_SERVICE_URL + "/api/v1/order/vaccine-center/"
    vaccine_types_resource = settings.PANEL_SERVICE_URL + "/api/v1/order/vaccine-type/"

    # Request Json
    request_json = {}

    request_json["order_id"] = id

    # Get Response
    try:
        response = requests.post(requests_string, json=request_json,
                                 headers={'API-KEY': settings.PORTAL_API_KEY})
    except Exception as e:
        debug_logger.debug(get_formatted_log(
            request.path,
            status.HTTP_500_INTERNAL_SERVER_ERROR,
            str(e),
            request.user
        ))
        return redirect("panel:500")

    try:
        vaccine_centers = requests.post(vaccine_centers_resource,
                                        headers={'API-KEY': settings.PORTAL_API_KEY})
    except Exception as e:
        debug_logger.debug(get_formatted_log(
            request.path,
            status.HTTP_500_INTERNAL_SERVER_ERROR,
            str(e),
            request.user
        ))
        return redirect("panel:500")

    parsed_response = json.loads(response.content)
    if len(parsed_response['content']) >= 1:
        parsed_response['content']['status_val'] = order_status[0][parsed_response['content']['status']]
        if parsed_response['content']['payment_type'] is not None:
            parsed_response['content']['payment_type_val'] = payment_status[0][
                parsed_response['content']['payment_type']]
        else:
            parsed_response['content']['payment_type_val'] = "Unpaid"
        parsed_response['content']['person_number'] = len(parsed_response['content']['persons'])
        parsed_response['content']['payment_remaining'] = float(parsed_response['content']['amount']) - float(
            parsed_response['content']['paid_amount'])
        if parsed_response['content']['is_used_coupon']:
            parsed_response['content']['discount'] = float(
                parsed_response['content']['hotel_package']['price']) - float(parsed_response['content']['paid_amount'])
        else:
            parsed_response['content']['discount'] = "-"

    parsed_vaccine_centers = json.loads(vaccine_centers.content)

    next_step = DONE
    if parsed_response["content"]["status"] == WAITING_FOR_RECEIVING_SECOND_DOSE:
        next_step = DONE

    # Get Vaccines
    try:
        vaccine_types_response = requests.post(vaccine_types_resource, json=request_json,
                                               headers={'API-KEY': settings.PORTAL_API_KEY})
    except Exception as e:
        debug_logger.debug(get_formatted_log(
            request.path,
            status.HTTP_500_INTERNAL_SERVER_ERROR,
            str(e),
            request.user
        ))
        return redirect("panel:500")

    parsed_vaccine_types = json.loads(vaccine_types_response.content)

    return render(request, "panel/detail.html",
                  {'id': id, 'info': parsed_response, "vaccine_centers": parsed_vaccine_centers["content"],
                   "next_step": next_step, "vaccine_types": parsed_vaccine_types["content"]})


@login_required
def order_edit(request, id):

panel/templates/user/login.html
{% extends "base.html" %}

{% load i18n %}

{% load static %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static "users/login.css" %}">
{% endblock head %}

{% block content %}

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 limiter no-padding">
                <div class="container-login login_bg">
                    <div class="wrap-login">

                        <div id="loading" class="wrap-login__loading-wrapper">
                            <div class="wrap-login__loading-wrapper__loading spinner-grow" role="status">
                            </div>
                        </div>
                        <form action="#" id="login-form" method="post" class="login-form validate-form">
                            {% csrf_token %}
                            <span class="login-form-logo">
                                <img src="/backend/static/assets/images/logo.jpg">
                            </span>
                            <span class="login-form-title">
                                {% trans 'Sign in' %}
                            </span>
                            <div class="wrap-input100 validate-input" data-validate="Enter username">
                                <input autocomplete="off" class="input100" type="text" name="username" placeholder="">
                                <span class="focus-input100" data-placeholder="{% trans 'username' %}"></span>
                            </div>
                            <div id="submit-button" class="wrap-input100 validate-input" data-validate="Enter password">
                                <input autocomplete="off" class="input100" type="password" name="password" id="password"
                                       placeholder="">
                                <span class="focus-input100" data-placeholder="{% trans 'password' %}"></span>
                            </div>
{#                            <div class="contact100-form-checkbox">#}
{#                                <input class="input-checkbox" id="remember" type="checkbox" name="remember">#}
{#                                <label class="label-checkbox100" for="ckb1">#}
{#                                    {% trans 'remember_me' %}#}
{#                                </label>#}
{#                            </div>#}
                            <div class="container-login-form-btn">
                                <button class="login-form-btn">
                                    {% trans 'Sign in' %}
                                </button>
                            </div>
                            <div id="container-login__message" class="container-login__message">

                            </div>
{#                            <div class="text-center" style="margin-top: 20px">#}
{#                                <a class="txt1" href="">#}
{#                                    {% trans 'dont_remember' %}#}
{#                                </a>#}
{#                            </div>#}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>

        jQuery(function ($) {

            /* [Focus input] */
            $('.input100').each(function () {
                $(this).on('blur', function () {
                    if ($(this).val().trim() != "") {
                        $(this).addClass('has-val');
                    } else {
                        $(this).removeClass('has-val');
                    }
                })
            })

            /* [Validate] */
            $("#login-form").submit(function (event) {

                event.preventDefault();

                // check for empty inputs
                if ($("input[name=username]").val() == "") {

                    showErrorMessage("please insert your username");
                    return false;

                } else if ($("input[name=password]").val() == "") {

                    showErrorMessage("please insert your password");
                    return false;

                }

                // storing form's action url in variable
                var url = $(this).attr('action');

                // serializing forms data for reading by name attr in server
                var data = $(this).serializeArray();

                $("#loading").css("display", "block");

                // send forms data to server
                $.ajax({
                    type: "POST",
                    url: url,
                    data: data,
                    dataType: "json",
                    success: function (response) {

                        $("#loading").css("display", "none");
                        window.location.href = "{% url "panel:labs" %}";

                    }
                    , error: function (response) {

                        $("#loading").css("display", "none");

                        if ("status" in response && "responseJSON" in response) {
                            showErrorMessage(response.responseJSON.message);
                        }

                    }
                });

            });

            function showErrorMessage(message) {
                $("#container-login__message").fadeIn();
                $("#container-login__message").text(message);
                setTimeout(function () {
                    $("#container-login__message").fadeOut();
                }, 1500);
            }

            function redirectPost(url, data) {
                var form = document.createElement('form');
                document.body.appendChild(form);
                form.method = 'post';
                form.action = url;
                for (var name in data) {
                    var input = document.createElement('input');
                    input.type = 'hidden';
                    input.name = name;
                    input.value = data[name];
                    form.appendChild(input);
                }
                form.submit();
            }

        });

    </script>

{% endblock %}